from pathlib import Path
import hashlib
import re

source_path = Path(r"C:\Users\c\Documents\카카오톡 받은 파일\vmware-mirror-ol10-migration-runbook.html")
output_path = Path(r"C:\Users\c\OneDrive\문서\등촌프로젝트\output\runbook\vmware-mirror-ol10-migration-runbook_쉬운설명추가.html")
src = source_path.read_text(encoding="utf-8")
out = output_path.read_text(encoding="utf-8")

# Remove only the blocks generated by add_easy_explanations.py.
cleaned = re.sub(r"\s*/\* 아래 easy-explain 블록.*?(?=\n  </style>)", "", out, count=1, flags=re.S)
cleaned = re.sub(r"\s*<aside class=\"easy-explain\".*?</aside>\s*", "\n", cleaned, flags=re.S)

print("source bytes:", len(src.encode("utf-8")))
print("output bytes:", len(out.encode("utf-8")))
print("easy explanation blocks:", len(re.findall(r"<aside class=\"easy-explain\"", out)))
same_ignoring_whitespace = re.sub(r"\s+", " ", cleaned).strip() == re.sub(r"\s+", " ", src).strip()
print("original content preserved after removing additions (whitespace ignored):", same_ignoring_whitespace)
print("doctype count:", out.count("<!doctype html>"))
print("html open/close:", out.count("<html"), out.count("</html>"))
print("style open/close:", out.count("<style"), out.count("</style>"))
print("source sha256:", hashlib.sha256(src.encode("utf-8")).hexdigest())
print("cleaned sha256:", hashlib.sha256(cleaned.encode("utf-8")).hexdigest())
